/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void addTwoPositive() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(2,2),4);
    }
	  @Test public void addSumZero() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(2,-2),0);
    }
	  @Test public void addTwoNegative() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(-2,-2),-4);
    }

	  @Test public void addSumNegative() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(-5,2),-3);
    }
	  @Test public void addSumPositive() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.add(-2,5),3);
    }

}
